function EUCASTBreakpoints = importEUCASTBreakpoints(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EUCASTBREAKPOINTSTIDY = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a cell
%  array.
%
%  EUCASTBREAKPOINTSTIDY = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  EUCASTBreakpointsTidy = importfile("/Users/RobertBeardmore/Dropbox/EUCAST-ECOFF/EUCAST-Docs/EUCAST Breakpoints Tidy.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Nov-2022 13:37:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Bacteria", "Antibiotic", "S", "R"];
opts.VariableTypes = ["char", "char", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Bacteria", "Antibiotic"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Bacteria", "Antibiotic"], "EmptyFieldRule", "auto");

% Import the data
EUCASTBreakpoints = readtable(filename, opts);

%% Convert to output type
EUCASTBreakpoints = table2cell(EUCASTBreakpoints);
numIdx = cellfun(@(x) ~isnan(str2double(x)), EUCASTBreakpoints);
EUCASTBreakpoints(numIdx) = cellfun(@(x) {str2double(x)}, EUCASTBreakpoints(numIdx));
end